---
abstract: 'CSRF tokens generation and validation'
author:
  - 'Oleg Nurtdinov <jumpercc@cpan.org>'
  - 'Jose M. Fernandez <jose.m.fernandez@bsc.es>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-CSRF
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SaltedHash: '0'
  Dancer2: '0.200001'
  Data::UUID: '0'
  perl: '5.01'
version: '1.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
